services:
  # bot:
  #   build:
  #     context: ./bot
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   volumes:
  #     - C:\Users\chris\Desktop\Projects\jellygram\appdata/bot:/data
  
  bot-net:
    build:
      context: ./bot-net
      dockerfile: Dockerfile
    container_name: bot-net
    restart: always
    env_file:
      - .env
    volumes:
      - C:\Users\chris\Desktop\Projects\jellygram\appdata/bot-net:/data
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - C:\Users\chris\Desktop\Projects\jellygram\appdata/backend:/data
    ports:
      - "8000:8000"
    restart: unless-stopped
