services:
  bot-net:
    build:
      context: ./bot-net
      dockerfile: Dockerfile

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
