services:
  # bot:
  #   build:
  #     context: ./bot
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   volumes:
  #     - C:\Users\chris\Desktop\Projects\jellygram\appdata/bot:/data
  
  bot-net:
    build:
      context: ./bot-net
      dockerfile: Dockerfile
    container_name: bot-net
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./appdata/bot-net:/data
      # Import & Download directories (writeable for downloading)
      - /mnt/disco/70-79_Media/Peliculas:/data/import/movies
      - /mnt/disco/70-79_Media/Series:/data/import/shows
    environment:
      - JELLYFIN_MOVIES_DIR=/data/import/movies
      - JELLYFIN_SHOWS_DIR=/data/import/shows
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./appdata/backend:/data
    ports:
      - "8005:8000"
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: jellygram-web
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - VITE_JELLYFIN_URL=${JELLYFIN_URL:-http://192.168.1.15:8096}
      - VITE_JELLYFIN_TOKEN=${JELLYFIN_TOKEN:-}
